[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "nl_sgtk"
version = "0.4.3"
description = "Nolabel's ShotGrid Toolkit helpers."
readme = "README.md"
requires-python = ">=3.8"
authors = [
    {name = "Nolabel"},
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "shotgun_api3>=3.10.0",
    "sgtk @ git+https://github.com/shotgunsoftware/tk-core.git@v0.23.6",
    "urllib3>=2.0.0",
]

[project.urls]
Homepage = "https://github.com/nolabel/nl_sgtk"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
